// Static full-name -> nickname map for MLB (30), NBA (30), MLS (29) teams + a
// partial UCL marquee set. UCL has 145 rotating clubs (incl. qualifiers), so most
// fall back to their full name (already short, never wrong) — only long marquee
// names are shortened here (exact DB names, verified 2026-08-05).
// (NFL legs fall back to full names — no NFL block here yet; harmless, NFL offseason)
// (docs/superpowers/plans/2026-07-28-leg-team-names.md).
//
// Naive last-token splitting is WRONG: it collapses "Boston Red Sox" and
// "Chicago White Sox" to the same "Sox", and turns "Toronto Blue Jays" into
// just "Jays". A full-name lookup table is the only correct approach for a
// fixed 30-team league.
const TEAM_NICKNAMES: Record<string, string> = {
  "Arizona Diamondbacks": "Diamondbacks",
  "Atlanta Braves": "Braves",
  "Baltimore Orioles": "Orioles",
  "Boston Red Sox": "Red Sox",
  "Chicago Cubs": "Cubs",
  "Chicago White Sox": "White Sox",
  "Cincinnati Reds": "Reds",
  "Cleveland Guardians": "Guardians",
  "Colorado Rockies": "Rockies",
  "Detroit Tigers": "Tigers",
  "Houston Astros": "Astros",
  "Kansas City Royals": "Royals",
  "Los Angeles Angels": "Angels",
  "Los Angeles Dodgers": "Dodgers",
  "Miami Marlins": "Marlins",
  "Milwaukee Brewers": "Brewers",
  "Minnesota Twins": "Twins",
  "New York Mets": "Mets",
  "New York Yankees": "Yankees",
  "Oakland Athletics": "Athletics",
  "Philadelphia Phillies": "Phillies",
  "Pittsburgh Pirates": "Pirates",
  "San Diego Padres": "Padres",
  "San Francisco Giants": "Giants",
  "Seattle Mariners": "Mariners",
  "St. Louis Cardinals": "Cardinals",
  "Tampa Bay Rays": "Rays",
  "Texas Rangers": "Rangers",
  "Toronto Blue Jays": "Blue Jays",
  "Washington Nationals": "Nationals",
  "Atlanta Hawks": "Hawks",
  "Boston Celtics": "Celtics",
  "Brooklyn Nets": "Nets",
  "Charlotte Hornets": "Hornets",
  "Chicago Bulls": "Bulls",
  "Cleveland Cavaliers": "Cavaliers",
  "Dallas Mavericks": "Mavericks",
  "Denver Nuggets": "Nuggets",
  "Detroit Pistons": "Pistons",
  "Golden State Warriors": "Warriors",
  "Houston Rockets": "Rockets",
  "Indiana Pacers": "Pacers",
  "Los Angeles Clippers": "Clippers",
  "Los Angeles Lakers": "Lakers",
  "Memphis Grizzlies": "Grizzlies",
  "Miami Heat": "Heat",
  "Milwaukee Bucks": "Bucks",
  "Minnesota Timberwolves": "Timberwolves",
  "New Orleans Pelicans": "Pelicans",
  "New York Knicks": "Knicks",
  "Oklahoma City Thunder": "Thunder",
  "Orlando Magic": "Magic",
  "Philadelphia 76ers": "76ers",
  "Phoenix Suns": "Suns",
  "Portland Trail Blazers": "Trail Blazers",
  "Sacramento Kings": "Kings",
  "San Antonio Spurs": "Spurs",
  "Toronto Raptors": "Raptors",
  "Utah Jazz": "Jazz",
  "Washington Wizards": "Wizards",
  "Atlanta United FC": "Atlanta Utd",
  "Austin": "Austin",
  "CF Montreal": "Montréal",
  "Charlotte": "Charlotte",
  "Chicago Fire": "Fire",
  "Colorado Rapids": "Rapids",
  "Columbus Crew": "Crew",
  "DC United": "D.C. United",
  "FC Cincinnati": "Cincinnati",
  "FC Dallas": "Dallas",
  "Houston Dynamo": "Dynamo",
  "Inter Miami": "Inter Miami",
  "Los Angeles FC": "LAFC",
  "Los Angeles Galaxy": "LA Galaxy",
  "Minnesota United FC": "Minnesota Utd",
  "Nashville SC": "Nashville",
  "New England Revolution": "Revolution",
  "New York City FC": "NYCFC",
  "New York Red Bulls": "Red Bulls",
  "Orlando City SC": "Orlando City",
  "Philadelphia Union": "Union",
  "Portland Timbers": "Timbers",
  "Real Salt Lake": "RSL",
  "San Jose Earthquakes": "Earthquakes",
  "Seattle Sounders": "Sounders",
  "Sporting Kansas City": "Sporting KC",
  "St. Louis City": "St. Louis",
  "Toronto FC": "Toronto",
  "Vancouver Whitecaps": "Whitecaps",
  // UCL (partial — most of the 145 clubs fall back to full names):
  "Paris Saint Germain": "PSG",
  "Manchester City": "Man City",
  "Manchester United": "Man Utd",
  "Bayern München": "Bayern",
  "Borussia Dortmund": "Dortmund",
  "Atletico Madrid": "Atlético",
  "Bayer Leverkusen": "Leverkusen",
  "Eintracht Frankfurt": "Frankfurt",
  "Red Bull Salzburg": "Salzburg",
  "Shakhtar Donetsk": "Shakhtar",
  "Olympiakos Piraeus": "Olympiakos",
  "Club Brugge KV": "Club Brugge",
  "BSC Young Boys": "Young Boys",
};

// Map lookup, fallback to the full name for anything unmapped (never wrong,
// just longer) and null-safe (a null/missing team name renders as null so
// callers can skip the line gracefully).
export function nickname(fullName: string | null): string | null {
  if (fullName === null) return null;
  return TEAM_NICKNAMES[fullName] ?? fullName;
}
